### PR TITLE
Add command line options for new bitdepth, dither, and colors options.

### PR DESCRIPTION
**Pull request by aaronblondeau**
Note - also switched the command line arguments parser to [yargs](https://github.com/yargs/yargs) as [optimist](https://github.com/substack/node-optimist) is deprecated.

### CODE REVIEW

**Comment by martinheidegger** [comment]
Awesome! Thank you for using yargs! Do the new settings not have defaults? ([hint](https://github.com/martinheidegger/mapslice/blob/master/lib/defaultSettings.js))

**Comment by aaronblondeau** [comment]
Due to the lack of a clear default for these options (besides dither), I set them up so that they have no effect when they are not present.

**Comment by martinheidegger** [comment]
Hmm, is there no clear default in gm docs?

**Comment by aaronblondeau** [comment]
The default behavior is to omit these options rather than supply a specific value for them.  For example, if no bitdepth option is provided, the gm.bitdepth method is not called at all.  The GraphicsMagick docs do not mention defaults for these, http://www.graphicsmagick.org/GraphicsMagick.html#details-colors, http://www.graphicsmagick.org/GraphicsMagick.html#details-depth, http://www.graphicsmagick.org/GraphicsMagick.html#details-dither

**Comment by martinheidegger** [comment]
Thank you for researching this information! LGTM

**Comment by martinheidegger** [comment]
Sorry, it took a while. Now mapslice@1.3.0 contains the fix, cheers!

**Pull request merged**
